apiVersion: v1
kind: Secret
metadata:
    name: sec
    labels:
        app.kubernetes.io/name: nextcloud
        app.kubernetes.io/instance: nextcloud
type: Opaque
stringData:
    nextcloud-username: ENC[AES256_GCM,data:aVt8vMM=,iv:X3POxlZtIqNhBkOZOAqwomGZTxxJeandhQfIlQi1wqo=,tag:kjW7SwP3FZ5MAGRsBi6SeA==,type:str]
    nextcloud-password: ENC[AES256_GCM,data:fuUgC05b37zrGSv61YXn5RqIstg=,iv:PNNEDtBRNRB6G9/xr9XnQyW3l4WPJxpPAp7/H8TGrzM=,tag:8cncBdj8M8CSjM4nn4yH8g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12wqzdg27tdlumxeg4qcr6pcypa9lpmtzwgtvulkcjlz6s9dmes5skdfazk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2TGlST3BFYjh3U0JWdXBh
            VmNCVCs4U29hMkJ4a05ERFJuK0tISUIvMDBrCk4xVnhBNE9YcEFBM09KamxXOE5K
            ZE5xK2VMTzFXc21NRFFOaFBGejJCWVkKLS0tIFZjNUQrRXBQVm9nODQxc0ZuK0Z2
            ZWR3aXFlN3kwTlk1bHM1cngwWWZRQmMKhrfgOnI/wxrRIJwSG+b9CR1TVp7K65Vb
            nuUziK3NkX0sS10P89YzyYHdGFBn0QkCGeb4BWtWVC9SizMDhuNjGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-14T13:20:39Z"
    mac: ENC[AES256_GCM,data:O43b0IQiLvgRv97r+NjSmc7zSyZpL5ae/xpqUT1xGZnOCGYthLwfN6rb8MtHnSc/pqGptXrBs2InWq2/5kNq2sEJySPo+MVIPb/lnho7B2mSzjcQv285OdGqgNV7HlkAeKkcoqdQI1t7wml9GzUdsFlS06OK4sdqYl1Gr5/141A=,iv:Co3WcRItKgNJW11qLzbey9VBXNHS7eM/y0Ef6hKhAfM=,tag:D4JwK6sIiGIdBV1hBgcXmA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
