apiVersion: v1
kind: Secret
metadata:
    name: sec
    labels:
        app.kubernetes.io/name: nextcloud
        app.kubernetes.io/instance: nextcloud
type: Opaque
stringData:
    nextcloud-username: ENC[AES256_GCM,data:1WCx6OM=,iv:VhQw+Fgp0ZB3m0lE41Xa+QL3XjMIPjgX6G109QPhMxw=,tag:3beav0w43RbPm1OLXnzR0A==,type:str]
    nextcloud-password: ENC[AES256_GCM,data:z2SbtVozPCAykbR6U9Lj3ryS+G0=,iv:vfRRSKPCBjMTzeys5aU/CwsfftTVfv6+300Mh8Kgj5g=,tag:hRBqRj/V58oFMdjTGo7l3g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rvaq4w6qmddrec5jhpetg68cglj7cg7x9uk9uf95mg5jc9y2s49srvwz84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoN1hrbEZrNjlTcEJyUUZj
            SStVU1F4MThxT1lJSUJxa1hiVCtKWGN4dHdZCjJOQVNVS0VnOCt2SlJIVXF3SUh5
            YlAwOFR1T1N3dG95UUV5cWYycG5hTVEKLS0tIHRISytxL3ZnNVNyeE50OHI5U0RY
            bTVkSVRETGZrVWtjQ1JGMVpsTHJrK3cK//yflIlSRdnGqZVVNA3nBIg0qw34mTbN
            VmEJVYfYFvZ42ru5/jAuyYL8N6Rue5Y5qWvwkPGlECLrIDLXIOqQ6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-15T19:55:52Z"
    mac: ENC[AES256_GCM,data:6jFxD5T3F313pHmct7A3fqATkmO4cDsshtekevskL3W61mv32LtctB+FrpkCVUFRam8KueyxwOv/7G1XqFgGm47DgugmguueejSNpxuiH1Do8WhsB2Zy0XdSuOiQqbszQVYkALMcZW72jHdwW8PFyaQMHGO+MTHrI+vOrgs+Syk=,iv:NLezoPryw2RFHwSaPXJ1qqqRkTolDw1m1/V38ufJlQI=,tag:Zd4ZE16Bf7bIRmUNBeqouA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
