apiVersion: v1
kind: Secret
metadata:
    name: sec
stringData:
    username: ENC[AES256_GCM,data:dJyKZ38=,iv:i0xu2XOfw79aDWllFcCgGLmynqe/ULj7FLQA3/mIhec=,tag:Rm3+N/71YGLWoCnTgQb+Uw==,type:str]
    password: ENC[AES256_GCM,data:duRRyLCat7j6s4ysyba770iVCp4=,iv:frqc/kxiwBd1nRTKh0uWPn8grZTDoQ5un4joZ5axAUM=,tag:SN7AQwvgVbjZGCjx2Qhb9g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12wqzdg27tdlumxeg4qcr6pcypa9lpmtzwgtvulkcjlz6s9dmes5skdfazk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQWlVhR1Ztd0ttdmpGb2Ix
            S2Q0Z1ZHVEhjdE94aUg4NEMyZ3VnTDRzdzNrCkl4R0dweGcyVVczMmw1Q2tVNmRF
            U1IrUTJVYXViRFlUbXdlaFRQN0NPS0EKLS0tIFJ2TzBUcFFmbUxDZmdNYXhNZEpY
            M2lMU1Fib3JhZWFPL3IrTWYzUXRIWjgKV3w/QR18nYvWk1rwZojM1fz3R3TxvgGq
            J5vBCYlQTqZ75UjsXeJdi7Y0v0wHyw1z/FY1EPavuHOhEVMaKHvW4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-14T13:20:10Z"
    mac: ENC[AES256_GCM,data:6acADz3bL3RsG6g754HeZd5DsKV7uj4do5hFQNDfg3vLcLtuyhHL7jP7F20+lGEg4pC1jy/esckt0J81M3QYMuloz6NqYqxWCcSz9Pic0EKuxn3cbq5jokQf8jGrbTCAEoXRAv4sNAx9zyOqSwqG3zbBV2WRLeoLQcZEoyLMFkw=,iv:WvJeNqaZXC5vUWktL9fzIZUKzOugcxfvE9nhqfzYMJk=,tag:Al7QqhnvN8lrAN7tGP8LGw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
