apiVersion: v1
kind: Secret
metadata:
    name: sec
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:SdGuMG5yAtpl139QAxjzAYCbxJg=,iv:0++KuBP//lnUG4IVVvulEUjS9uEI+5AZaRuYNDyRMl4=,tag:HlnwoTw8FDoubUOAcPnKiA==,type:str]
    username: ENC[AES256_GCM,data:OvNhywRC,iv:A4vHirV9WYU/Dk9xlKC4WQbHnDrxVgc9UsLnDFzRwhM=,tag:XSgp+qfZeGvgPCHkn+Fumw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rvaq4w6qmddrec5jhpetg68cglj7cg7x9uk9uf95mg5jc9y2s49srvwz84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGVFRiTjRpOHJxOUpkQ2Vj
            MWE3RHFuVnRDbkIwSjI5eEdOTFY4ODdrc1NrCjAxTWFVZmNpTHV4RzZoTGNKeHEz
            RmsxMDdLNzJPd0JtN0paL21rQ0lDVFkKLS0tIDhNOWRaWkE5SXFWTG45KzBGK3lt
            azg2ZVFmM2t6QnA1VnkrbTVzbjEvQlkKLNvcD3BvdmKETtcH8yOmTh2bG26U5yc6
            9aZWcdP5jrcKs7RJoHd36i63fxJx5mlsgI2/G4eOFm4lxOo3vJqI3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-15T19:55:41Z"
    mac: ENC[AES256_GCM,data:8LAGQd2dH/22c2mJA/bRXDB4PJNA2dgS9ensOM4Nd68k6JKOPsPPIqG/kSwjxtkWnYOoExGwjwr9p6fAXQ1TsZ4QtLJFF7GnTL6uUIknLY9WV1f/y1/Pwam5jo7FVxY5+OJKNd/egnUEMW+xWPYgjdBbOpOsGlPfONuPdGJUXGM=,iv:7r1uGFDRtBukfKpJx9CZH7Swwp1B2WYmqMsuOgvoGJo=,tag:ZQhrXa5VH0r+BcASj2MYEg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
