apiVersion: v1
kind: Secret
metadata:
    name: sec
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:fmiTdBnzrYA9KBk24eLaq7sAJ1Y=,iv:wXX57dnys4Zwbu9xSQyM8wW65eg/oajD/7ZaL9ev4Os=,tag:/op2MXaHkKY8clEeqyBODw==,type:str]
    username: ENC[AES256_GCM,data:1+mVJ/Kg,iv:l8KAoefbO1lhpm1bLoqr2nd12s3o8yRYkNxrjMbfGdc=,tag:K3eP78tp5i8PqZd6eekk4A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12wqzdg27tdlumxeg4qcr6pcypa9lpmtzwgtvulkcjlz6s9dmes5skdfazk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkRzZQMlVxRWR5Y0Z3dUhF
            d1Y2djN3MmE0NE5tVUorQVM0QXZPN05TZlhZCmI5cDB5WVd5b2RpZFU4V3JseUFQ
            T0ZoczN6TjZlWTNrUDJVU3p6bW1FeVEKLS0tIDYwSFE2Nk5BZ1R3a0pER1EzTC9m
            VHJ5ZWxzWklDYnRmeWhyYkxETStOd2cKUtJsrxUSUAVMDrnKLde1iGnBmJTeJIby
            0WRbpNmpSnp/5BojZ0lWtlhwFluAJHKgQ2Z4lnu2PAx4/UCFiEXjyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-14T13:20:54Z"
    mac: ENC[AES256_GCM,data:xj0xSnEjdSmJWhd5HXv/nDxobpAhAzXoDAatWbVYQfZV+EkQAaPvuiFfl47IteJUzFMQyXhY2r6Qzz23PbOLM3/EBDBeean3sMFmVs09FmCChwS6L7Khnapn75WPaYYUDWoPeyhkiRql0L5yesWHmCO0rV/6SzXnugVcDItd90M=,iv:e6phMBc9hU3Upht2JYGAiq0i7SfRnHoNs0Tp2+sSF4I=,tag:dMAz4Bxty7hTpvTqtb3vLA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
