apiVersion: v1
kind: Secret
metadata:
    name: sec-super
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:UrDAmWvNcKj04PjNgHzVnEOro3Y=,iv:MCgw+1Xbx1piOoK3lCJa4w+lM9EExM9MB1bBeuXTOos=,tag:sVq6qpzZ7KQzKDPZBjHUmg==,type:str]
    username: ENC[AES256_GCM,data:4/pbZB7Dhds=,iv:VcChpr3VsHeHS+kBoabQWjpEy3GO2KOhAEH/ngF+Qw8=,tag:qSKRhjAkCgmrBOPbWpE1BQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rvaq4w6qmddrec5jhpetg68cglj7cg7x9uk9uf95mg5jc9y2s49srvwz84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYRisxMGpLSml3V1ZzL0N1
            VS90VW9qc3F6cGkwTWtsWUpnRElmbkdrUVd3ClZoMzdXTkloU2VBSk5ld1puODFI
            S1ByNHVRZThPbUlHM1BqTmRTcFM3V0kKLS0tIDV2SGxSdHAxeWNLcjRCSEhiRC8x
            U2RmQ0oxSlpVVlpNajZFTW1WbTFpQUkKFf9m+kh3KTu+AXvyAn3N73EV8VeTUN6u
            NBug/LVhEIvWhWgv0lOdinDrSgfco949TNMjErOPcmTuO/SROlDZlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-15T19:55:45Z"
    mac: ENC[AES256_GCM,data:goEmAaiWLX/TfuJ96S3oMJ/OV3JdgDXu9k6Ehoyhe766ebH/pavLV3YtojiaJFdM4zmwXw8EML8J85SkPUAOwxgdBmC55iScO3+Pg07onMyb1/VrmvjMFH4NFWPDMXBUcFGw+aXJ/blMLfK1BgElb0+e3Dpgt1wWfeM+REUS0lw=,iv:aBAkWu1cYtIqy+M6ItyUxODlhtB97z8BEwwDRLDE3PE=,tag:3QMVJYlOUKkCStXKNb6+2w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
