apiVersion: v1
kind: Secret
metadata:
    name: sec-super
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:X02y5XTxWZtiiZmkxB0FLrdZEks=,iv:PJAjauVKSX1zDD0VKkzWL1UJW2n7C0Kat641BwRU29w=,tag:eJYnSciRxL3JvFsun00+lg==,type:str]
    username: ENC[AES256_GCM,data:QhTaLTnWxnA=,iv:sjuVGTKFmszpTHe48tXnNcvyvaRHpSmR+gIzM0X00EM=,tag:gaB8al5BENjo1KjtUE2I+Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12wqzdg27tdlumxeg4qcr6pcypa9lpmtzwgtvulkcjlz6s9dmes5skdfazk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtaEF3Sy9yUWk1emJGbjNw
            QjZmQUtVSGR4T3lyVVJURThBdThaZnhjTUhRCk1LUHRXVGQxYm8vNDZCWU8yaU4y
            MVR1WXlRVm5YT25EYkxob3VWV1RQdlkKLS0tIE1tTXpEZGN2czN5RlVMOW5ncU1s
            L243VTZ3dnRMNHgxK1ZISklSRlB3dG8KbNFvjA589kvPVHpIzT02IhXdtjrtrm4N
            Y9Et7ddfvJbA7gxeBIl9muCLNfwGXyfOpGzUlh2e0z/DILRHN+xb4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-14T13:20:51Z"
    mac: ENC[AES256_GCM,data:3edLLiVda0zlOSvv2ziKWsW5IBWIchvCcfHdj+9Pt/IsOHV5gN+QICpsgk09Oqh6P827hrqJtNfNkiJP5Nl+2UP5kLkt8l9jJhiLYZsNLF7PBpQoPLB/Nhrmbb72VdaaAHaZr5am7xIAicZI36BYhab35+0bQkLVGjfFSouC1Do=,iv:WTrOKMcJnia/F6Qxe2jhF9T1kIJb9pGLukpDMZpfJMw=,tag:Zi5bFoUNpekPyIo49sqavQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
