apiVersion: v1
stringData:
    minio_root_user: ENC[AES256_GCM,data:HF4J2Y3Ukaf79Jm2uFXlo9nv4PY=,iv:iKPkAH+MLr0JHaWUHVzBCt9m3xRQ51XCbviPX4ATBpI=,tag:Lqdbt19YBIzcHKkdRDbywA==,type:str]
    minio_root_password: ENC[AES256_GCM,data:E9a6NzrokKcRL1VIYITkyjaYK8Q=,iv:U3e0rKhEGxl+8Km7iEtbVoa/kRVZSBQOORgLZgwkYXM=,tag:02qnruE1TIaAgow6+8PG+Q==,type:str]
kind: Secret
metadata:
    name: sec
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12wqzdg27tdlumxeg4qcr6pcypa9lpmtzwgtvulkcjlz6s9dmes5skdfazk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNOHlkR0tKT1pnQlUxVXQ1
            bGNFZGVXbVNtMkRJWjhZOEI2NkJSVmNDb2tvCm5rS3JEM0xDMkt5T3pCTEtTVzlw
            STJuZXIzcCtHbkhCcVY4cXZqSjI0WEkKLS0tIFhWNU9kK1dpSVN3aDdiVTdqZWww
            Nk5CSWJpUEZ6Ynh2dTV5ZzdEQldod00KkIsAxzhkLZCGfp85accz83xWeE9DcbPG
            8t/SrgCF8AU0UcDsUxrG4W36oa//5vNkmnzsdwTo/cnWdrLV7tskNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-14T13:20:29Z"
    mac: ENC[AES256_GCM,data:IWAfrMj13Qf2O52yFgQpc/LzWNJz6S17C59OPDBgaMo7v6Bfy3MY2Iw0jeQyvhsnLaDZMI8VMXXQUqUn7cXlzG5iMJRNyuswXboVDnn45QyrWd11UELb6rtH4T6Vi7k8TmNPanuP15Z2QzjVcK8iyz0J2XXw8RVftJOV83PcZ8I=,iv:0nKs3P8gIniKT1bt9/Kh1/pc9GDUmoIt4+PoryLp9Vg=,tag:iAfi7WnzaEGn4ZknaDbs2Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
