apiVersion: v1
stringData:
    minio_root_user: ENC[AES256_GCM,data:zFF0qPYWkpnoZO1poiFM9f7IP60=,iv:NVGRvWncyUTnqLtgBxPxBZnOlBuCST7pnwNCk8x/8dc=,tag:yQxJ+3IPSYIKTodDMZoAlA==,type:str]
    minio_root_password: ENC[AES256_GCM,data:Cud0xsWfPYVnW/G8EeUxEJryGe0=,iv:MenGzTLcZ20DsOMJLjyQgDnGrauKmEVX+GUxHvtNGFM=,tag:3RHyfWDNRK4FpLU24m+TRg==,type:str]
kind: Secret
metadata:
    name: sec
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rvaq4w6qmddrec5jhpetg68cglj7cg7x9uk9uf95mg5jc9y2s49srvwz84
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXRTlNNnFBQ3pOMzB5TTZn
            dk0rQjFrb0FYUXliOWlIN3M2TWRyc3l1SGdFCjV2YU8ydXB6ZGY4dzYrcks4SW1a
            b0lmUzFjZkpCRnE1cWJ6YndCNVhDQUEKLS0tIG44ZjZmQWlhRm5nZU92blZrMGpy
            VHl1R3RuUWZkK29xcFB0MmVzSm9yaWsKJBLuMP6/vCKVFWNcxafudaFAEgI07VUK
            qMNXVffjeKCwU/9sSYf3U6Lpvls9HWnjNeV0Kcvgg4F7QzQaV6tz/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-15T19:56:00Z"
    mac: ENC[AES256_GCM,data:4pJSLBLHjr+qYtmasdMJCsNXGAKUCz5wV2okWKh3Yv21XcO6/H2pZrbOzVXWLQSvI1xg8o3yAhqNUH+ItCmvcngfL8OX30lh0tb5v3DNV+fi9Ggd6yCkYV9V9NdxUFREZ2dk0PpEokUEr4YBW0ctok/hZ4XZw97bgi7PoC0Rr1k=,iv:63qJxNR8gQOMIK5fQEK8FWO8tLM4DdLPP/MyfaamaYE=,tag:DGVua8C8AylmGCpVH2d08Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
